# Add GPU functionality to the shell

# CudaNN                                                                           
if [ "$LD_LIBRARY_PATH" == "" ]; then                                             
  export LD_LIBRARY_PATH=/usr/local/cuda/lib64                                    
else                                                                              
  export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH                   
fi                                                                                
export CUDA_HOME=/usr/local/cuda                                                   

