# Add dev functionality to the shell

plugins+=( \
  git \
  git-flow-avh \
  redis-cli \
  kubectl \
  zsh-syntax-highlighting \
  fast-syntax-highlighting \
  zsh-autosuggestions \
  #zsh-autocomplete \
)

# CCACHE on non-portage                                                            
[ -d "/usr/lib/ccache/bin" ] && export PATH="/usr/lib/ccache/bin:$PATH"

for env in "${devenvs[@]}"; do
  [ -f "$DOTS/includes/dev/envs/${env}.sh" ] && \
      source $DOTS/includes/dev/envs/${env}.sh
done
