# Add dev functionality to the shell

plugins+=( \
    git-flow-avh \
    redis-cli \
)

# CCACHE on non-portage                                                            
[ -d "/usr/lib/ccache/bin" ] && export PATH="/usr/lib/ccache/bin:$PATH"

for env in "${devenvs[@]}"; do
  [ -f "$DOTS/includes/dev/envs/${env}.sh" ] && \
      source $DOTS/includes/dev/envs/${env}.sh
done
