incs=( \
    arch \
    dev \
    laptop \
    layout \
    gpu \
    games \
)

devenvs=( \
  cloud \
  javascript \
  python \
  ruby \
)

for inc in "${incs[@]}"; do
    source $DOTS/includes/$inc/zshrc
done
